{% set version = "2.0.0" %}

package:
  name: twine
  version: {{ version }}

source:
  fn: twine-{{ version }}.tar.gz
  url: https://pypi.io/packages/source/t/twine/twine-{{ version }}.tar.gz
  sha256: 9fe7091715c7576df166df8ef6654e61bada39571783f2fd415bdcba867c6993

build:
  noarch: python
  number: 0
  script: python -m pip install --no-deps --ignore-installed .
  entry_points:
    - twine = twine.__main__:main

requirements:
  host:
    - pip
    - python >=3.6
    - setuptools >=0.7.0
  run:
    - python >=3.6
    - pkginfo >=1.4.2
    - readme_renderer >=21.0
    - requests >=2.20
    - requests-toolbelt >=0.8.0,!=0.9.0
    - setuptools >=0.7.0
    - tqdm >=4.14

test:
  imports:
    - twine
    - twine.commands
  commands:
    - twine --help

about:
  home: https://github.com/pypa/twine
  license: Apache  2.0
  license_family: Apache
  license_file: LICENSE
  summary: 'Collection of utilities for interacting with PyPI'

extra:
  recipe-maintainers:
    - jankatins
    - SylvainCorlay
